group_config:
  other:
    legend: ''
    models:
      - 'alpaca-7b-reproduced'
      - 'beaver-7b-v1.0'
    labels:
      - 'SFT'
      - 'Safe RLHF'
    color: 'black'
    marker: 'X'
  one_step:
    legend: 'One-step alignment'
    models:
      - 'helpful_dpo_0.1'
    labels:
      - 'DPO (H)'
    color: 'blue'
    marker: 'o'
  helpful_dpo_safety_dpo:
    legend: 'SACPO: DPO (H) -> DPO (S)'
    models:
      - 'helpful_dpo_safety_dpo_0.1'
      - 'helpful_dpo_safety_dpo_0.05'
      - 'helpful_dpo_safety_dpo_0.025'
      - 'helpful_dpo_safety_dpo_0.01'
    labels:
      - '0.1'
      - '0.05'
      - '0.025'
      - '0.01'
    color: 'red'
    marker: '>'
  linear_merging:
    legend: 'P-SACPO'
    models:
      - 'linear_0.25'
      - 'linear_0.5'
      - 'linear_0.75'
    labels:
      - '0.25'
      - '0.5'
      - '0.75'
    color: 'green'
    marker: 's'